#!/usr/bin/env bash

courseName="$1"

templateFile=~/course/.homeworkTemplate.org
styleFile=~/course/latex_styles/homework.sty
makeHomeworkFile=~/course/.makeHomework

function main {
    if [ ! -d "$courseName" ]; then
        mkdir "$courseName"
        mkdir "$courseName"/homework
        
        ln -s $makeHomeworkFile "$courseName"/homework/make
        ln -s $templateFile "$courseName"/homework/template.org
        ln -s $styleFile "$courseName"/homework/homework.sty
        
        requestAddToGit
    fi;
}
    
function requestAddToGit {
    while true; do
        read -p "Add to git? [Y/n]: " yn
        case $yn in
            Y) addToGit; break;;
            n) exit;;
        esac
    done    
}

function addToGit {
    git restore --staged `git diff --name-only --cached`    
    git add "$courseName"
    git commit -m "Added $courseName"
}

main $@
    
    
