#!/usr/bin/env bash

function main {
    [ -z "$1" ] && error "Provide a course name" || courseName="$1"
    templateFile=.homeworkTemplate.org
    styleFile=latex_styles/homework.sty
    makeHomeworkFile=.makeHomework
    
    if [ ! -d "$courseName" ]; then
        prepareHomeworkDirectory
        requestAddToGit
    fi;
}

function prepareHomeworkDirectory {
    homework="$courseName"/homework
    mkdir -p $homework
    cd $homework
    ln -s ../../$makeHomeworkFile make
    ln -s ../../$templateFile template.org
    ln -s ../../$styleFile homework.sty
    cd ../..
}

function requestAddToGit {
    while true; do
        read -p "Commit \"$courseName\" to git? [Y/n]: " yn
        case $yn in
            Y) addToGit; break;;
            n) exit;;
        esac
    done    
}

function commitToGit {
    git restore --staged `git diff --name-only --cached`    
    git add "$courseName"
    git commit -m "Added $courseName"
}

function error {
    echo "ERROR: $1"
    exit 1
}

main $@
    
    
